server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:academia
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
