server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:academia
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
